# 服务器端口和项目名称配置
server:
  port:8081
# 数据库配置
spring:
  datasource:
    name: weaponsystem
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc::mysql://localhost:3306/weaponsystem?userUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    data-username: root
    data-password: pp970928
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml